# documentation: https://yarnpkg.com/configuration/yarnrc

compressionLevel: 0

enableGlobalCache: true

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-3.1.1.cjs

logFilters:
  - code: "YN0005"
    level: "discard"
  - code: "YN0076"
    level: "discard"
  - pattern: "@workspace:examples"
    level: "discard"
  - pattern: "@storybook/root@workspace:."
    level: "discard"
  - pattern: "@workspace:addons/storyshots/"
    level: "discard"